import Header  from "@/components/Header";
import Footer from "@/components/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    // absolute:"Layout", //optional field - This ignores title.template set in parent segments. Not recommended in Layout.tsx and can be defined only in page.tsx 
    default:"Default Title", // optional field given if page.tsx does not have title attribute. this will be shown.
    template:"%s | NextJSApp" // to append or prepend any tiitle before or after.
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
